---

- name: IPTables
  ansible.builtin.include_tasks:
    file: iptables/main.yaml
    apply:
      tags:
        - always
  tags:
    - always
  when: >
    firewall_type | lower == 'iptables'


- name: Fail2ban
  ansible.builtin.include_tasks:
    file: fail2ban/main.yaml
    apply:
      tags:
        - always
  tags:
    - always
  when: >
    install_fail2ban | bool
