---

- name: Pre-task check
  ansible.builtin.fail:
    msg: You must define a firewall type.
  when: >
    firewall_type is not defined
      or
    firewall_type | default('') == ''


- name: IPTables
  ansible.builtin.include_tasks:
    file: iptables.yaml
    apply:
      tags:
        - always
  tags:
    - always
  when: firewall_type | lower == 'iptables'


- name: Fail2ban
  ansible.builtin.include_tasks:
    file: fail2ban.yaml
    apply:
      tags:
        - always
  tags:
    - always
  when: >
    ansible_os_family == "Debian"
      and
    install_fail2ban | bool
