---

- name: IPTables Installed Check
  ansible.builtin.apt:
    name:
      - iptables
    state: present
  check_mode: true
  register: check_iptables_installed


- name: IPTables Install
  ansible.builtin.include_tasks:
    file: iptables/install.yaml
    apply:
      tags:
        - always
  tags:
    - always
  when: >
    firewall_type | lower == 'iptables'
      and
    not check_iptables_installed


- name: IPTables Configure
  ansible.builtin.include_tasks:
    file: iptables/configure.yaml
    apply:
      tags:
        - always
  tags:
    - always
  when: >
    install_fail2ban | bool
      and
    firewall_installed | default(false)
